### ISSUE TITLE
Wire connect diagram

### ISSUE THREAD

**Issue by fengmin2611** [MatthiasLienhard/opencat_micropython#1]
Hello,
Can you share the details of the wire connect diagram? How can remote control it?
Thank you very much

**Comment by MatthiasLienhard** [comment]
The project is premature state and wiring is not finished as I am adding new features. I use a esp32 development board that has (1s li ion) battery management included. The servos are controlled by a PCA9685 i2c PWM controller (powered by the battery, which is suboptimal - 4.2V is fine, but on load voltage drops below what is ok for the 9g servos), and a HCSR04 ultrasonic distance sensor module which is powered by 5V (there is a step up regulator on the dev board), and wired to pin 14 and 12 (with a voltage divider at the output, since the signals are 5V). I also have a cheap amplifier module connected to the DAC for audio, and a MPU6050 to i2c, that is not used so far. If you have specific questions let me know.

**Comment by MatthiasLienhard** [comment]
Ah, remote control is done with the micropython repl while the code runs in background. Telnet provides means to control it with wifi. Maybe i will add a mobile app eventually. So far I focused on the auto-mode which is triggered by touching pin 13.
